/// Flutter icons Hello_bloc
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Hello_bloc
///      fonts:
///       - asset: fonts/Hello_bloc.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomFontIcon {
  CustomFontIcon._();

  static const _kFontFam = 'Hello_bloc';

  static const IconData mosque = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData islam = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData newspaper = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData quran_rehal = IconData(0xe805, fontFamily: _kFontFam);
}
